# Generated by Django 5.2.14 on 2026-05-17 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('query_text', models.TextField(help_text='Original RM natural-language query')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('message_text', models.TextField(blank=True)),
                ('dispatch_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_records', to='campaigns.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outreach_records', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Outreach Record',
                'verbose_name_plural': 'Outreach Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['created_by', 'status', 'created_at'], name='campaigns_c_created_0a99d0_idx'),
        ),
        migrations.AddIndex(
            model_name='outreachrecord',
            index=models.Index(fields=['campaign', 'dispatch_status'], name='campaigns_o_campaig_99a6e1_idx'),
        ),
    ]
