# Generated by Django 5.2.14 on 2026-05-17 15:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('pan', models.CharField(max_length=10)),
                ('aadhaar', models.CharField(max_length=12)),
                ('account_number', models.CharField(max_length=20)),
                ('annual_income', models.DecimalField(db_index=True, decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit_score', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(900)])),
                ('emi_ratio', models.DecimalField(db_index=True, decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('tenure_years', models.PositiveSmallIntegerField(default=0)),
                ('savings_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('last_login', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('marketing_consent', models.BooleanField(db_index=True, default=False)),
                ('do_not_contact', models.BooleanField(db_index=True, default=False)),
                ('has_active_dispute', models.BooleanField(default=False)),
                ('has_active_fd', models.BooleanField(default=False)),
                ('loan_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField(db_index=True)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('avg_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-month'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['annual_income', 'credit_score'], name='customers_c_annual__49d15a_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['credit_score', 'emi_ratio'], name='customers_c_credit__b74c57_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['kyc_status', 'do_not_contact', 'marketing_consent'], name='customers_c_kyc_sta_c33de2_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_login', 'tenure_years'], name='customers_c_last_lo_0a93d6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'month'], name='customers_t_custome_767349_idx'),
        ),
    ]
